server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: 'http://localhost:3100'


scrape_configs:
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /run/log/journal
      labels:
        job: systemd-journal

    relabel_configs:
      - source_labels: ['__journal__pid']
        target_label: 'pid'
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'instance'
      - source_labels: ['__journal__comm']
        target_label: 'cmd'
